---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - icb4dc0.de.icb4dc0.de
  resources:
  - floatingips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - icb4dc0.de.icb4dc0.de
  resources:
  - floatingips/finalizers
  verbs:
  - update
- apiGroups:
  - icb4dc0.de.icb4dc0.de
  resources:
  - floatingips/status
  verbs:
  - get
  - patch
  - update
